### ISSUE TITLE
Not working good with other contexts

### ISSUE THREAD

**Issue by funkyduke** [modxcms/pThumb#13] opened 2013-12-03 00:08 UTC
When I use pthumb in combination with other context (languages) then the thumbs are not created. You can see by example what I mean.

Correct: http://www.quilombo.eu/home/nieuws/2013/11/11/spekkenfestival2013/

Not correct (french site): http://www.quilombo.eu/fr/home/nieuws/2013/11/11/spekkenfestival2013/

I have followed the instructions of Babel to setup the different contexts and did this before on past websites (with succes). This is however the first website I use pthumb.

Can somebody please help me, it's urgent.

**Comment by funkyduke** [comment] 2013-12-03 14:08
Found a solution: http://forums.modx.com/thread/88002/pthumb-and-multilanguage-site

**Comment by oo12** [comment] 2013-12-04 15:11
Glad you figured out a solution.  There might be an improvement I could make in the code though, so it'd work right to begin with.

I imagine the problem is that it can't locate the input image when the context is something besides web?  From your example on the MODX forums, would you mind posting the values of the [[+imageTV]] and [[++base_url]] tags, for a resource in both for the 'web' and 'fr' contexts?

If the site is already live, just add something like

```
 <!-- imageTV:[[+imageTV]] | base_url: [[++base_url]] -->
```

to the template, then view the page source on the front end.

**Comment by funkyduke** [comment] 2013-12-04 15:57
img src="[[+imageTV:replace=`[[++base_url]]==/`:pthumb=`w=145&h=145&zc=1`]]"

Web: 
fr: 

---

img src="[[+imageTV:pthumb=`w=145&h=145&zc=1`]]"

Web: img src="/assets/image-cache/Elena/Portfolio/spookhuis/spookhuis3.b12a6b15.jpg"
fr: img src="/fr/assets/userfiles/Elena/Portfolio/spookhuis/spookhuis2.jpg"

**Comment by oo12** [comment] 2013-12-06 04:45
Yes, the problem is that the input path is wrong:  `/fr/assets/userfiles/Elena/Portfolio/spookhuis/spookhuis2.jpg` doesn't exist; what you want is `/assets/userfiles/Elena/Portfolio/spookhuis/spookhuis2.jpg`.

I added a fix for this though in pThumb 2.2.2-pl.  It'll check whether the specified file—the first one—exists, and if it's not found it'll remove base_url (`/fr` in this case) and try again.  So you don't need to use the replace output filter any longer.

**Closed as completed by oo12** 2013-12-06 04:45 UTC
